# Configurazione di AdvancedBanSystem
settings:
  log-actions: true # Abilita/disabilita il logging delle azioni
  ban-message: "Sei stato bannato dal server!"
  unban-message: "Sei stato sbannato dal server."
  blacklist-message: "Non sei consentito su questo server."